-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 17:50:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pams` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pams` ;

-- -----------------------------------------------------
-- Table `pams`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`branch` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `branch_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `pams`.`city` (`city_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`property` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `branch_id` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `property_ibfk_1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `pams`.`branch` (`branch_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`apartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`apartment` (
  `apartment_id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `apartment_number` VARCHAR(20) NOT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `rooms` INT NULL DEFAULT NULL,
  `monthly_rent` DECIMAL(10,2) NOT NULL,
  `status` ENUM('AVAILABLE', 'OCCUPIED', 'UNDER_MAINTENANCE') NULL DEFAULT 'AVAILABLE',
  PRIMARY KEY (`apartment_id`),
  INDEX `property_id` (`property_id` ASC) VISIBLE,
  CONSTRAINT `apartment_ibfk_1`
    FOREIGN KEY (`property_id`)
    REFERENCES `pams`.`property` (`property_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`tenant` (
  `tenant_id` INT NOT NULL AUTO_INCREMENT,
  `ni_number` VARCHAR(20) CHARACTER SET 'ucs2' NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `occupation` VARCHAR(100) NULL DEFAULT NULL,
  `reference` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tenant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`complaint` (
  `complaint_id` INT NOT NULL AUTO_INCREMENT,
  `tenant_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `status` ENUM('SUBMITTED', 'IN_REVIEW', 'RESOLVED') NULL DEFAULT 'SUBMITTED',
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_date` DATETIME NULL DEFAULT NULL,
  `resolution_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`complaint_id`),
  INDEX `tenant_id` (`tenant_id` ASC) VISIBLE,
  INDEX `apartment_id` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `complaint_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `pams`.`tenant` (`tenant_id`)
    ON DELETE CASCADE,
  CONSTRAINT `complaint_ibfk_2`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `pams`.`apartment` (`apartment_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`lease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`lease` (
  `lease_id` INT NOT NULL AUTO_INCREMENT,
  `tenant_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `monthly_rent` DECIMAL(10,2) NOT NULL,
  `status` ENUM('ACTIVE', 'TERMINATED', 'EXPIRED') NULL DEFAULT 'ACTIVE',
  `early_termination_penalty` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`lease_id`),
  INDEX `tenant_id` (`tenant_id` ASC) VISIBLE,
  INDEX `apartment_id` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `lease_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `pams`.`tenant` (`tenant_id`)
    ON DELETE CASCADE,
  CONSTRAINT `lease_ibfk_2`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `pams`.`apartment` (`apartment_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `lease_id` INT NOT NULL,
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `amount_due` DECIMAL(10,2) NOT NULL,
  `due_date` DATE NOT NULL,
  `status` ENUM('PENDING', 'PAID', 'LATE') NULL DEFAULT 'PENDING',
  PRIMARY KEY (`invoice_id`),
  INDEX `lease_id` (`lease_id` ASC) VISIBLE,
  CONSTRAINT `invoice_ibfk_1`
    FOREIGN KEY (`lease_id`)
    REFERENCES `pams`.`lease` (`lease_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('FRONT_DESK', 'FINANCE_MANAGER', 'MAINTENANCE_STAFF', 'ADMIN', 'MANAGER', 'TENANT') NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tenant_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `branch_id` (`branch_id` ASC) VISIBLE,
  INDEX `tenant_id` (`tenant_id` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `pams`.`branch` (`branch_id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `pams`.`tenant` (`tenant_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`maintenance_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`maintenance_request` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `tenant_id` INT NULL DEFAULT NULL,
  `apartment_id` INT NULL DEFAULT NULL,
  `priority` ENUM('LOW', 'MEDIUM', 'HIGH') NULL DEFAULT 'LOW',
  `description` TEXT NOT NULL,
  `status` ENUM('REPORTED', 'IN_PROGRESS', 'RESOLVED') NULL DEFAULT 'REPORTED',
  `reported_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `assigned_staff_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `tenant_id` (`tenant_id` ASC) VISIBLE,
  INDEX `apartment_id` (`apartment_id` ASC) VISIBLE,
  INDEX `assigned_staff_id` (`assigned_staff_id` ASC) VISIBLE,
  CONSTRAINT `maintenance_request_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `pams`.`tenant` (`tenant_id`)
    ON DELETE SET NULL,
  CONSTRAINT `maintenance_request_ibfk_2`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `pams`.`apartment` (`apartment_id`)
    ON DELETE CASCADE,
  CONSTRAINT `maintenance_request_ibfk_3`
    FOREIGN KEY (`assigned_staff_id`)
    REFERENCES `pams`.`user` (`user_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`maintenance_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`maintenance_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `request_id` INT NOT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `hours_spent` DECIMAL(5,2) NULL DEFAULT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `resolution_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `request_id` (`request_id` ASC) VISIBLE,
  CONSTRAINT `maintenance_log_ibfk_1`
    FOREIGN KEY (`request_id`)
    REFERENCES `pams`.`maintenance_request` (`request_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`notification` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `type` ENUM('LATE_PAYMENT', 'MAINTENANCE_UPDATE', 'GENERAL') NULL DEFAULT 'GENERAL',
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notification_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pams`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pams`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pams`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `lease_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_method` VARCHAR(50) NULL DEFAULT NULL,
  `card_last4` VARCHAR(4) NULL DEFAULT NULL,
  `transaction_reference` VARCHAR(100) NULL DEFAULT NULL,
  `validated` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`payment_id`),
  INDEX `invoice_id` (`invoice_id` ASC) VISIBLE,
  INDEX `lease_id` (`lease_id` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `pams`.`invoice` (`invoice_id`)
    ON DELETE CASCADE,
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`lease_id`)
    REFERENCES `pams`.`lease` (`lease_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
